version: 0.2

env:
  variables:
    S3_BUCKET: "inst-clone"
    FOLDER_NAME: "calculator-app"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Android SDK..."
      # This is the corrected wget command with a plain URL
      - wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android-sdk.zip
      - mkdir -p $HOME/android-sdk/cmdline-tools
      - unzip -q android-sdk.zip -d $HOME/android-sdk/cmdline-tools
      - mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
      - export ANDROID_HOME=$HOME/android-sdk
      - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      - yes | sdkmanager --licenses
      - sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

  pre_build:
    commands:
      - chmod +x ./gradlew
      
  build:
    commands:
      - echo "Building release APK..."
      - ./gradlew assembleRelease

  post_build:
    commands:
      - echo "Build successful. Uploading APK to S3..."
      - aws s3 cp app/build/outputs/apk/release/app-release.apk s3://$S3_BUCKET/$FOLDER_NAME/app-release.apk

artifacts:
  files:
    - app/build/outputs/apk/release/app-release.apk
  discard-paths: yes
